# Project information

site_name: Integrating security into your container pipeline
site_short_name: Container DevSecOps
site_description: 'In this hands-on workshop, you will learn to leverage AWS development tools and open-source projects to integrate automated security testing into a CI/CD pipeline to build and release hardened container images.  You will learn about common security concerns within containers and discuss a variety of patterns for creating security-centric release control into an AWS CodePipeline.  Additionally, you'll learn how to add feedback loops to ensure your developers are quickly able to respond to security issues within their container-based applications.'
site_url: 'https://container-devsecops.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-container-devsecops-workshop'
repo_url: 'https://github.com/aws-samples/aws-container-devsecops-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - 'Module 1: Environment Setup': '01-env-setup.md'
  - 'Module 2: Dockerfile Linting': '02-linting.md'
  - 'Module 3: Secrets Scanning': '03-secrets-scanning.md'
  - 'Module 4: Vulnerability Scanning': '04-vuln-scanning.md'
  - 'Cleanup: Discussion': 'cleanup.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'